### PR TITLE
chore: Rebuild Vectord2D

### PR DESCRIPTION
**Pull request by naschidaniel**
I have tried to reimpliment `Vector2D`.
Currently I am failing with the type `Vector2D(0.5547 0.8321)`? 
@hiaselhans, do you have a hint?

### CODE REVIEW

**Comment by hiaselhans** [comment]
hey daniel! great!

the idea was to have most operations immutable:
https://airgproducts/euklid/blob/a2c53fbbc844f37adfb7945efaa88a4f1314c7e3/src/vector/vector.cpp#L139

how can this be done in rust?

**Comment by naschidaniel** [comment]
Yesterday I found a way with `struct Vector2D (f64, f64)`.

**Comment by naschidaniel** [comment]
@hiaselhans,

the functionality of [euklid](https://github.com/airgproducts/euklid) has been replicated.
The functions `angle()`, `copy()`, `cross()`, `dot()`, `normalized()` and `length()` are available for a `Vector2D`.

The PR is ready.

**Comment by hiaselhans** [comment]
sehr cool!

**Pull request merged**
